modLoader="javafml"
loaderVersion="[43,)" 
license="MIT"

[[mods]]
modId="lolenderite"
version="1.5-1.19.2"
displayName="Enderite"
logoFile="enderite_logo.png"
displayURL="https://www.youtube.com/@lieonlion"
updateJSONURS="https://github.com/LieOnLion"
authors="LieOnLion"
description='''
      !!ANNIVERSARY EDDITION!!
This past Year has been amazing and
its because of all you amazing People

Adds Enderite to the Game :]
'''