modLoader="javafml"
loaderVersion="[45,)"
license="MIT"

[[mods]]
modId="lolenderite"
version="1.8-1.19.4"
displayName="Enderite"
logoFile="enderite_logo.png"
displayURL="https://www.youtube.com/@lieonlion"
updateJSONURS="https://github.com/LieOnLion"
authors="LieOnLion"
description='''
Adds Enderite to the Game :]
'''

[[dependencies.lolenderite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"